### ISSUE TITLE
Fastcli underreports the download speed

### ISSUE THREAD

**Issue by martinbrose** [n8henrie/fastcli#5]
- **Operating system and version**: macOS Monterey Version 12.3.1
- **Python version**: 3.6 and 3.9 in Conda virtual environments
- **fastcli version**: 0.1.1

## My Issue
Fastcli underreports my download speed consistenly.
When I run fast.com in Safari, it shows a download speed of approx 400+ Mbps.
When I run fascli in the terminal, my speed is approx 130-180 Mbps only.

<img width="1031" alt="Screenshot 2022-04-24 at 10 37 51" src="https://user-images.githubusercontent.com/13284268/164970344-a80dce4c-0b07-4ba4-becd-a0e597bc8873.png">

<img width="248" alt="Screenshot 2022-04-24 at 10 37 12" src="https://user-images.githubusercontent.com/13284268/164970340-1f17268d-bf32-4d4c-b7f3-cb719a953bf1.png">

**Comment by martinbrose** [comment]
I have just tested this on my Raspberry Pi 4, which is connected via network cable to my router. 
With a Conda Python 3.9 virtual environment, I receive only a result of approx 50 Mbps.

**Comment by n8henrie** [comment]
I think you might be right about this, though I'm getting a much less dramatic difference.

Comparing against the built-in Apple utility `networkQuality`:

Lines beginning with `Download capacity:` are from `networkQuality`, starting with `Approximate` is `fastcli`:

```
Approximate download speed: 32.69 Mbps
Download capacity: 37.183 Mbps
Approximate download speed: 38.27 Mbps
Download capacity: 64.543 Mbps
Approximate download speed: 24.29 Mbps
Download capacity: 41.162 Mbps
Approximate download speed: 15.81 Mbps
Download capacity: 49.720 Mbps
Approximate download speed: 29.41 Mbps
Download capacity: 75.999 Mbps
Approximate download speed: 38.08 Mbps
Download capacity: 49.278 Mbps
Approximate download speed: 27.33 Mbps
Download capacity: 25.385 Mbps
Approximate download speed: 24.85 Mbps
Download capacity: 23.053 Mbps
Approximate download speed: 12.90 Mbps
Download capacity: 50.327 Mbps
Approximate download speed: 29.91 Mbps
Download capacity: 44.352 Mbps
Approximate download speed: 30.02 Mbps
Download capacity: 26.268 Mbps
Approximate download speed: 21.48 Mbps
Download capacity: 41.174 Mbps
Approximate download speed: 19.99 Mbps
Download capacity: 33.754 Mbps
Approximate download speed: 22.41 Mbps
Download capacity: 33.070 Mbps
Approximate download speed: 18.48 Mbps
Download capacity: 67.814 Mbps
Approximate download speed: 48.82 Mbps
Download capacity: 52.871 Mbps
Approximate download speed: 31.57 Mbps
Download capacity: 18.899 Mbps
Approximate download speed: 27.09 Mbps
Download capacity: 22.429 Mbps
Approximate download speed: 30.38 Mbps
Download capacity: 16.971 Mbps
Approximate download speed: 16.99 Mbps
Download capacity: 10.688 Mbps
```

That gives averages of Apple: 39.247, fastcli: 27.0385 

Comparing with https://github.com/sindresorhus/fast-cli I get 55 with fast-cli and 39 with fastcli.

So it definitely seems like I'm getting lower results with this library. I wonder why? Thanks for pointing this out!

**Comment by n8henrie** [comment]
It looks like this is the implementation that HomeAssistant uses: https://github.com/nkgilley/fast.com (a fork of https://github.com/sanderjo/fast.com, which is where I originally forked the project).

Differences I see:
- larger chunk size (1024 * 100)
- https://github.com/nkgilley/fast.com/blob/master/fastdotcom/__init__.py#L34
    > \# convert bytes (at application layer) to bits (at network layer)
     return bytes * 8 * 1.0415

**Comment by n8henrie** [comment]
It also looks like that library is reporting the *highest* speed from a number of threads, whereas mine reports the *average* speed:  https://github.com/nkgilley/fast.com/blob/master/fastdotcom/__init__.py#L169
